USE Library

CREATE TABLE Authors
(
	Id INT PRIMARY KEY IDENTITY,
	FirstName NVARCHAR(50) NOT NULL,
	LastName NVARCHAR(50) NOT NULL,
)
GO
CREATE TABLE Genre
(
	Id INT PRIMARY KEY IDENTITY,
	[Name] NVARCHAR(50) NOT NULL,
)
GO
CREATE TABLE Books
(
	Id INT PRIMARY KEY IDENTITY,
	Title NVARCHAR(50) NOT NULL,
	AuthorID INT NOT NULL FOREIGN KEY  REFERENCES Authors(Id),
	Price MONEY NOT NULL,
	Amount INT NOT NULL,
	GenreID INT NOT NULL FOREIGN KEY  REFERENCES Genre(Id),
)
GO